// Generated by gencpp from file rm_msgs/Referee.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_REFEREE_H
#define RM_MSGS_MESSAGE_REFEREE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Referee_
{
  typedef Referee_<ContainerAllocator> Type;

  Referee_()
    : is_online(false)
    , stamp()  {
    }
  Referee_(const ContainerAllocator& _alloc)
    : is_online(false)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint8_t _is_online_type;
  _is_online_type is_online;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::Referee_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Referee_<ContainerAllocator> const> ConstPtr;

}; // struct Referee_

typedef ::rm_msgs::Referee_<std::allocator<void> > Referee;

typedef boost::shared_ptr< ::rm_msgs::Referee > RefereePtr;
typedef boost::shared_ptr< ::rm_msgs::Referee const> RefereeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Referee_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Referee_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Referee_<ContainerAllocator1> & lhs, const ::rm_msgs::Referee_<ContainerAllocator2> & rhs)
{
  return lhs.is_online == rhs.is_online &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Referee_<ContainerAllocator1> & lhs, const ::rm_msgs::Referee_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Referee_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Referee_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Referee_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Referee_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Referee_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Referee_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Referee_<ContainerAllocator> >
{
  static const char* value()
  {
    return "407bdd83433e865cfa74911de122ad5c";
  }

  static const char* value(const ::rm_msgs::Referee_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x407bdd83433e865cULL;
  static const uint64_t static_value2 = 0xfa74911de122ad5cULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Referee_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Referee";
  }

  static const char* value(const ::rm_msgs::Referee_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Referee_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_online\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::Referee_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Referee_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_online);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Referee_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Referee_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Referee_<ContainerAllocator>& v)
  {
    s << indent << "is_online: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_online);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_REFEREE_H
